version: '3.8'

services:
  devopscasefront:
    build:
      context: . # O contexto para a construção da imagem Docker é o diretório atual
    container_name: devopscasefront
    ports:
      - '7676:80' # Mapeia a porta 80 do container para a porta 7676 da máquina local
    volumes:
      - .:/app # Mapeia o diretório atual do host para o diretório /app do container
      - /app/node_modules # Mapeia a pasta node_modules para persistir as dependências
    environment:
      - NGINX_PORT=80 # Define uma variável de ambiente NGINX_PORT no container
    networks:
      - webnet # Conecta o container à rede 'webnet'

networks:
  webnet: # Definindo a rede 'webnet'
    driver: bridge # O driver 'bridge' é usado para criar uma rede isolada
