version: '3.8'

services:
  frontend:
    build: .
    ports:
      - '5173:5173' # Porta que o Vite usa no modo de desenvolvimento
    volumes:
      - .:/app # Sincroniza o diretório de código local com o container
    environment:
      - NODE_ENV=development # Ambiente de desenvolvimento
    command: npm run dev # Comando para rodar o servidor Vite

