name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Ativa o deploy sempre que houver push na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Defina a versão do Node.js conforme necessário

    - name: Install dependencies
      run: |
        npm install
        npm run build

    - name: Vercel deploy
      run: |
        npm install -g vercel  # Instalar o CLI do Vercel globalmente
        vercel --token ${{ secrets.VERCEL_TOKEN }} --prod  # Executar o deploy na Vercel em produção
